[appendix]
[[app3]]

// The resource URLs should be under the control of Manning. The URLs
// should redirect to the relevant page. Before production, the
// attribute, resource-url, should be set to a Manning URL, preferably
// one that the author has access to make changes to. Especially the
// redirects. Each URL listed below should have a comment with the URL
// to redirect to.

//:resource-url: https://manning.com/grokking-bitcoin/resources
:resource-url: http://www.rosenbaum.se

== Web resources

// author, title, date, website name, URL

[[web-bitcoin-paper,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Satoshi Nakamoto, “Bitcoin: A
Peer-to-Peer Electronic Cash System,” 2008, http://mng.bz/lppR.
// https://bitcoin.org/bitcoin.pdf

[[web-stackexchange,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Bitcoin Stack Exchange,
http://mng.bz/BDDl.
// https://bitcoin.stackexchange.com

[[web-dev-ref,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Bitcoin Developer Reference,
http://mng.bz/dPP1.
// https://bitcoin.org/en/developer-reference

[[web-bitcoin-source,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Bitcoin source code repository,
http://mng.bz/rBBj.
// https://github.com/bitcoin/bitcoin

[[web-book-source,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Kalle Rosenbaum, source code
for _Grokking Bitcoin_, http://mng.bz/qBO2.
// ????  https://git.manning.com/agileauthor/rosenbaum

[[web-financial-inclusion,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: “Financial Inclusion Data /
Global Findex,” The World Bank, 2014, http://mng.bz/Vqqx.
// http://datatopics.worldbank.org/financialinclusion/

[[web-wikileaks-blockade,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: “Reception of WikiLeaks:
Response from the financial industry,” Wikipedia, http://mng.bz/gYnV.
// https://en.wikipedia.org/wiki/Reception_of_WikiLeaks#Response_from_the_financial_industry

[[web-cyprus-seizure,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Menelaos Hadjicostis, “Bank of
Cyprus Depositors Lose 47.5% of Savings,” USA Today, July 29, 2013,
http://mng.bz/pEez.
// https://www.bloomberg.com/news/articles/2013-07-30/cyprus-sets-levy-on-bank-of-cyprus-uninsured-depositors-at-47-5-

[[web-bips,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Bitcoin improvement proposals
(BIPs), GitHub, http://mng.bz/OA0E.
// https://github.com/bitcoin/bips/blob/master/README.mediawiki

[[web-bitcoin-wallets,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Choose Your Bitcoin Wallet,
http://mng.bz/xJJ6.
// https://bitcoin.org/en/choose-your-wallet

[[web-elliptic-curve-calculator,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Andrea Corbellini, “Elliptic
Curve Point Addition,” http://mng.bz/YOBA.
// https://cdn.rawgit.com/andreacorbellini/ecc/920b29a/interactive/modk-add.html

[[web-length-extension-attack,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Discussion of why double SHA256
is used in Bitcoin, Stack Exchange Cryptography, http://mng.bz/G2aO.
// https://crypto.stackexchange.com/questions/50017/why-hashing-twice

[[web-op-codes,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Complete list of Script
operators in Bitcoin, Bitcoin Wiki, http://mng.bz/A22Q.
// https://en.bitcoin.it/wiki/Script

[[web-bloom-filter-privacy,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Arthur Gervais,
Ghassan O. Karame, Damian Gruber, and Srdjan Capkun, “On the Privacy
Provisions of Bloom Filters in Lightweight Bitcoin Clients,”
Cryptology ePrint Archive, http://mng.bz/ZZZ9.
// https://eprint.iacr.org/2014/763.pdf

[[web-target-change,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Peter Todd, “What Attack Does
the Difficulty Drop Rate Limiter Prevent?”, http://mng.bz/zgWQ.
// https://petertodd.org/assets/commitments/52ccc4802bd563076cbd25ec4c1ba88152098cb6aa356ba644c9e79a24182da5.txt

[[web-lightinig-network,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Lightning Labs, Lightning
Resources, http://mng.bz/RGGa.
// https://dev.lightning.community/resources/index.html

[[web-bernanke-ascii-art,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: A blockchain explorer showing
the ascii-art transaction discussed in <<ch09>>, http://mng.bz/J88Q.
// https://tradeblock.com/bitcoin/tx/930a2114cdaa86e1fac46d15c74e81c09eee1d4150ff9d48e76cb0697d8e1d72

[[web-install,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Running a Full Node,
http://mng.bz/2AAw.
// https://bitcoin.org/en/full-node

[[web-download,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Bitcoin Core download page,
http://mng.bz/177R.
// https://bitcoincore.org/en/download/

[[web-getting-started,Web resource {counter:webresourceid}]]
Web resource {counter:webresourceid}:: Getting Started with Bitcoin,
http://mng.bz/P885.
// https://bitcoin.org/en/getting-started
