== Resolving privacy issues
:imagedir: {baseimagedir}/ch03

This chapter covers

* The privacy problem of the cookie sheet
* Fixing the privacy issues
* Creating Cookie Sheet addresses

'''
Problems:

* Everyone can see everybody's cookie eating habits

Solution1:

Pay to public keys instead of names, include your pubKey when paying.

Benefits:

* Lisa can ditch public key table
* Cookie habits are obfuscated
* Anyone can create an account without asking Lisa.
* Anyone can have multiple accounts

'''
Problems:

* You must write 66 hex digits for the payee

Solution2:

Hash the public key ripemd160(sha256(pubKey)) and use the hash instead
of pubKey in cookie sheet.

Benefits:

* Shorter strings (now 40 hex characters)
* Improved security on FIRST payment. P2PKH instead of P2PK

'''
Problems:

* People make typing mistakes
* People still thinks 40 characters are too long
* We are tired of making huge changes everywhere when the address
  format changes.

Solution3:

Add a version and a checksum to the pubKeyHash and base58 encode it.

Benefits:

* Future changes to the address format can be made less intrusively
* People will check their checksum before sending the pubKeyHash
* The address is only about 34 characters now.

'''
Problems:

* If the Ellen buys some cookie tokens from Hassan, then Hassan knows
  Ellens CT address, and pubkeyhash. He can then see all financial
  activity on that address and the address simply becomes a pseudonym
  for Ellen. If Mehmet know Ellen has that pseudonym, he knows
  everything about Ellens cookie habits. So we still have a privacy issue.

* Solution4:

People use uniqe CT addresses for all transactions.


People start to get concerned about privacy. Everybody can see exactly
how much cookies other people are eating. Lisa is also beginning to
hate to keep the table of public keys up-to-date. Another issue they
see is that the café cannot know who of two customers just paid
10 CT. It could be any one of them since the café don't know the names
of all coworkers.

They start using public keys instead of their names in the cookie
sheet. Lisa no longer have to keep the public key table. Good.

This works well, but there is one more problem: People sometimes make
typing errors when they type the public keys, both their own public
key and the public key of the recipient. Also people complain about
having to type the public keys as 64 charachter hex strings when paying.

They find a good way to hash the public key, and versioning it. They
also add a checksum to it and base58 encode it. Everyone can verify
the checksum on the notes.

Note now that no one needs to add his/her public key to Lisa
beforehand. People just hand their address to the payer, and the payer
pays to the address. This means that users can create as many
addresses as they want, and nobody is able to tell what addresses
belongs to John.

The café can now create a unique address for every purchase. That way
he knows exactly who pays, because only one customer has received a
certain address.
