= Minimum Qualified Reader

== Minimum skills and knowledge (3)

Generally, the reader does not need to have detailed knowledge on any
computer science topic. But she needs to have an abstract
understanding on some basic areas.

Network communication (3):: A basic understanding of how computers
communicate with each other. No knowledge about how the communication
works or anything about the physical structure of a computer network
is needed. Just an abstract understanding of how each computer have an
address and that messages can be sent between the computers.

Databases (2):: A reader must understand that a database is a "more or
less structured collection information". A text file containing phone
numbers to customers is a database, as well as the National Security
Agency's huge collection of snooped emails from/to average Joes.

Computer programs (2):: A computer program, or software program, must
be understood to be a set of instructions that a computer performs to
fullfill a certain task. One must understand that a software program
does not have to be something that you see on a computer screen, but
can just as well be somethng that collects temperature data from a
weather station and sends the data to another computer across a
computer network.

Web server (3):: A reader must know what a web server is. It is a
computer program that listens on a computer network for requests for
data and sends back the requested data. When you visit
http://www.google.com, your computer sends a request over a computer
network to a web server on a computer at Google. Google's web server
will then send back a web page that is displayed in your web browser.

== Takeaways

After reading this book, the reader will understand on a deep, but
still abstract, level what is going on under the hood of Bitcoin. She
will also understand why the technologies used are needed. For
example, she will understand that computers in the Bitcoin network
compete for rewards, by consuming electricity to produce a
proof-of-work, and that one reason for using proof-of-work is that no
one should be able to rewrite history.

The main focus will be on technically understanding the Bitcoin
system, but some chapters will be dedicated to teaching the reader how
to actually do stuff like sending and receiveing bitcoins, or how to
store your bitcoins safely.

Some of the takeaways from this book will

* understand on a deep level how Bitcoin works

* be able to decide whether you trust Bitcoin (or not)

* be able to validate use cases and come up with your own use cases

* help others understand and use Bitcoin

* debunk myths, there are plenty.

* join the conversation on future developments in Bitcoin

* obtain and store bitcoins

* send and receive bitcoins
