= Grokking Bitcoin


Kalle Rosenbaum
MEAP began May 2017  Publication in Summer 2018 (estimated)
ISBN 9781617294648  450 pages (estimated)  printed in black & white

If you think Bitcoin is just an alternative currency for geeks, it's
time to think again. Grokking Bitcoin opens up this powerful
distributed ledger system, exploring the technology that enables
applications for Bitcoin-based financial transactions as well as using
the blockchain for registering for example physical property
ownership. With this fully illustrated, easy-to-read technical guide,
you'll finally understand how Bitcoin works and decide for yourself
whether you trust Bitcoin or not. Along the way, you'll dive into the
underlying security and distributed system concepts that power
Bitcoin. Each chapter is loaded with diagrams and exercises to help
you gain a true understanding of each interesting topic. With the
fundamentals in place, you'll be able to validate Bitcoin use cases,
trustlessly use Bitcoin by running your own Bitcoin node and debunk
myths about Bitcoin. Of course, more simple tasks like setting up a
Bitcoin wallet and sending and receiving payments will become a
no-brainer, because you're grokking the fundamentals.

// [ TOC ]

== about the technology

The modern world turns on universally-accepted ideas of currency and
ownership. Bitcoin offer the potential to move control of these key
functions from change-prone governments to a global system controlled
by no one and everyone. This is achieved by letting every user verify
and store all financial transactions in their own copy of a global
public ledger called "the blockchain". Transactions stored on the
blockchain are, for all practical purposes, incorruptible; changing
data in the blockchain becomes increasingly expensive as the data
ages. In 2009 Bitcoin introduced the blockchain idea in combination
with proof-of-work and incentive mechanisms for use as an alternative
currency. Today, individuals, businesses, and institutions are using
Bitcoin as their weapon of choice for global commerce, savings,
speculation, risk diversification among other things.

== what's inside

// Not sure what's expected here. Is it
// a) (what kind of book this is)

* 450 pictures
* Bitcoin taught from the ground up
* Lots of easy-to-follow examples
* Many exercises ranging from easy to advanced

// b) (what you'll learn about) (the following bullets are similar to
//     what's already in the web copy)

* Send and receive bitcoins
* Bitcoin transactions
* The blockchain
* Bitcoin mining
* The Bitcoin peer-to-peer network

// or c) (what skills you'll achieve)

* decide whether you trust Bitcoin or not
* debunk myths, there are plenty
* validate Bitcoin use cases and come up with your own use cases
* evaluate proposed upgrades to the Bitcoin protocol
* send and receive bitcoins using any bitcoin wallet
* run your own node in the Bitcoin peer-to-peer network
* extract blockchain information from your node

== about the reader

This book provides a jargon-free introduction to Bitcoin for any
technically interested reader. It may be beneficial, but not required,
in some chapters to have a basic understanding of mathematics and
programming.

== about the author

Kalle Rosenbaum founded Popeller, a Bitcoin consultancy, in
2015. Kalle provides expert software development services and
education around Bitcoin.
